name: "VMWare Harbor"
description: "Project Harbor is an enterprise-class registry server that stores and distributes Docker images."
version: "1.2.0"
category: "Registry"
labels:
  io.rancher.orchestration.supported: 'kubernetes'
