apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-jobservice-config
  namespace: registry
data:
  UI_SECRET: "ik3o7H3feZaj4kDe"
  JOBSERVICE_SECRET: "iKyKgm8feFeafuEX"
  SECRET_KEY: "jB5pgJRV32at7YUT"
  MAX_JOB_WORKERS: "3"
  LOG_LEVEL: debug
  GODEBUG: netdns=cgo
  CONFIG_PATH: /etc/jobservice/app.conf
  config: |
    appname = jobservice
    runmode = dev
    [dev]
    httpport = 80
